name: Build to GKE

on:
  push:
    branches:
      - test

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IMAGE: test

permissions:
    contents: 'read'
    id-token: 'write'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/setup-gcloud@v0.3.0'
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Docker configuration
      run: |-
        gcloud auth configure-docker --quiet

    - name: Build
      run: |-
        docker build --tag "asia.gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" .

    - name: Publish
      run: |-
        docker push "asia.gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
