name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: test
      uses: kmasuda050/setup-python@test
    - name: test
      uses: kmasuda050/setup-python@test
      env:
        PYTHON_VERSION_REQUIRED: true
